---
  - name: Install supervisor
    pip: name=supervisor state=latest

  - name: Create supervisor directories
    file: >
      state=directory
      path={{ item }}
      mode=0755
    with_items:
      - "{{ supervisor_config_dir }}"
      - "{{ supervisor_conf_dir }}"
      - "{{ supervisor_log_dir }}"

  - name: Copy supervisor conf
    template: >
      src=supervisor.conf
      dest="{{ supervisor_config_dir }}/{{ supervisor_name }}.conf" 
      mode=0755

  - name: Create /etc/supervisord.conf symlink for supervisorctl to work with -c
    file: src="{{ supervisor_config_dir }}/{{ supervisor_name }}.conf" dest="/etc/supervisord.conf" state=link

  - include: setup-ubuntu.yml
    notify: Start supervisor
    when: ansible_distribution == 'Ubuntu' 

